# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josimar Camargo
email: josimarcamargo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notas de um desenvolvedor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://josimarcamargo.com" # the base hostname & protocol for your site
twitter_username: josimar_camargo
github_username:  josimarcamargo

permalink: /blog/:categories/:year/:month/:day/:title/

theme: jekyll-theme-architect

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jemoji # see emojis in development enviroment
